### ISSUE TITLE
Does not work on Firefox 57

### ISSUE THREAD

**Issue by RikuKawai** [cblknittights/ImageHost-Grabber#15]
The addon is no longer usable due to being a legacy addon.

I am not sure if it is possible to port to a WebExtension.

**Comment by cblknittights** [comment]
We will NOT be moving to the NEW "extensions" format.

There are several reasons why:

1) The API's needed are not provided.

2) Even if the API's were exposed, there is no current developer for the core code. Hosts ARE UPDATED as needed via our forum https://imagehostgrabber.com/forum/

Your options are to use the FF ESR 52.00 Branch, Revert to the older 56.0x and pin it in apt to not upgrade any further.

Use alternate browsers which WILL CONTINUE to use the EXISTING STANDARD for extensions. This includes Pale Moon, Sea Monkey, Waterfox, and a few others.
