### ISSUE TITLE
Retries failing or stalling in waterfox 12/19

### ISSUE THREAD

**Issue by cblknittights** [cblknittights/ImageHost-Grabber#20]
WF Classic 2019.12 works well. Installed over 1.7.0.4c. Only issue found is retry requests read "NaN of 10" and seem to hang for extremely long time (or forever).
[/quote]

**Comment by ghost** [comment]
just reproduced it. Reason is a typo. I will do some more testing and probably commit a fix later.

Edit:
I made the type with the fix for #19

**Comment by cblknittights** [comment]
This is corrected by fix 
https://github.com/cblknittights/ImageHost-Grabber/commit/a1dff2ed1b8133df5f045a3d30d3020d7363da1c

And thus closed.
