### ISSUE TITLE
What happened to https://www.imagehostgrabber.com/ ?

### ISSUE THREAD

**Issue by ghost** [cblknittights/ImageHost-Grabber#21]
The domain seems to be expired.
Are there any plans on how to continue?
The forum there was very useful.
Is there a new location for hostfile updates?
I hope everything is allright and well ...

(I do not have other means of communication, so I am creating this issue)

**Comment by HughJampton** [comment]
Just touching base, hoping for a resource to update hostfiles.

**Comment by ghost** [comment]
I would recommend a github project for the hostfile.

**Comment by firewaran** [comment]
I'd say we give @cblknittights a few days to look into it. 
Maybe the forum comes back online.

**Comment by ghost** [comment]
> I'd say we give @cblknittights a few days to look into it.
> Maybe the forum comes back online.

Yes of ourse, considering considering current affairs.
Many people have other, much more important things on their minds.

**Comment by ncilswdk2** [comment]
Not sure if this is related but seems like recently imagehostgrabber is much slower. Instead of a couple of seconds to find the images it takes 10-15 seconds. Last week, when I noticed this I went to the site to see if this was a wider issue and saw the site was down.

**Comment by ghost** [comment]
Yes, i is probably related. Disable host file auto update (Image Host Grabber -> Options -> Host File).

The update check cannot connect to imagehostgtabber.com and ime outs.

**Comment by ncilswdk2** [comment]
> Yes, i is probably related. Disable host file auto update (Image Host Grabber -> Options -> Host File).
> 
> The update check cannot connect to imagehostgtabber.com and ime outs.

Thanks. That worked.

**Comment by ghost** [comment]
https://imagehostgrabber.com/ is back again!

looks like somebody finally paid the bill ;-)
